[package]
name = "lison"
version = "0.1.0"
edition = "2024"

[dependencies]
cairo-rs = { version = "0.21.2", features = ["png"] }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"

[[bin]]
name = "lison-to-png"

[[bin]]
name = "lison-strip"
